### ISSUE TITLE
Training larger images

### ISSUE THREAD

**Issue by huahuasmi** [ioangatop/srVAE#7]
Thank you for writing such an excellent and convenient code！But when i trying to training larger images,there are errors about NAN in 'CALayer' modules.I don't understand why the conv2d outputs the NAN values?Looking forward to your answer~

**Comment by ioangatop** [comment]
Thank you for your kind words! There are two reasons why I believe this is happening:

1. Do you train with very small batch size, like 1?  This will trigger an error in the automatic data-driver parameter Initialisation. This can be an issue also in the RealNVP layers.

2. Because you changed the dimensionality of the input images, this will change the dimensionality of the latent codes **z**. This may trigger some errors on the parameters. Please, take a look at the NNs where the encoder and decoder define the `scale_factor`

For the encoder:
https://github.com/ioangatop/srVAE/blob/dfee765c53f11f4653e7c6e7118a339832656867/src/models/vae/image_networks/densenet32.py#L23

And for the decoder:
https://github.com/ioangatop/srVAE/blob/dfee765c53f11f4653e7c6e7118a339832656867/src/models/vae/image_networks/densenet32.py#L45

Please try to configure these values, while looking at the output dimensionality. They have to be the same as with the shape of the latent codes:
https://github.com/ioangatop/srVAE/blob/dfee765c53f11f4653e7c6e7118a339832656867/src/models/vae/vae.py#L35
